---
- name: Deploy AWX Survey
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    awx_api_url: "http://localhost:8081"
    awx_username: "awxcloudflare"
    awx_password: "Cloudflare@2025"
    job_template_id: 28
    platforms:
      - "G000"
      - "S009"
      - "T009"
  tasks:
    - name: Generate survey JSON
      ansible.builtin.template:
        src: roles/linux/cloudflare/awx_survey_setup/templates/survey_spec.json.j2
        dest: /tmp/survey_spec.json
      
    - name: Deploy survey to AWX
      ansible.builtin.uri:
        url: "{{ awx_api_url }}/api/v2/job_templates/{{ job_template_id }}/survey_spec/"
        method: POST
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        body: "{{ lookup('file', '/tmp/survey_spec.json') }}"
        body_format: json
        force_basic_auth: true
        status_code: [200, 201]
        validate_certs: false
      register: survey_result
      
    - name: Display result
      ansible.builtin.debug:
        msg: "Survey deployed successfully!"
